name: Labeling new issue
on:
- pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.1.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          default-labels: '["hacktoberfest","hacktoberfest-accepted"]'
